In [2]:
import pandas as pd
import numpy as np

In [6]:
occupation = pd.read_csv("/project/data_new/Data_OCCUPATION_AGE_UNIT.csv")

occupation.head()

,CDU_ID,GEO_CODE,GEO_LABEL,GEO_TYPE,GEO_TYP2,F349793,F349800,F349807,F349814,F349821,...,F350003,F350010,F350017,F350024,F350031,F350038,F350045,F350052,F350059,Unnamed: 41
0,NaN,NaN,NaN,NaN,NaN,Age : Age 16 to 24 - Economic activity : Econo...,Age : Age 16 to 24 - Economic activity : Econo...,Age : Age 16 to 24 - Economic activity : Econo...,Age : Age 16 to 24 - Economic activity : Econo...,Age : Age 16 to 24 - Economic activity : Econo...,...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,NaN
1,374.0,E09000007,Camden,Local Authorities,LA,494,1936,2155,1241,396,...,874,1670,983,436,203,212,185,142,340,NaN
2,379.0,E09000012,Hackney,Local Authorities,LA,535,2226,2628,1676,657,...,210,444,262,210,176,192,96,168,313,NaN
3,380.0,E09000013,Hammersmith and Fulham,Local Authorities,LA,570,2053,2459,1337,571,...,460,594,487,305,223,143,84,112,287,NaN
4,381.0,E09000014,Haringey,Local Authorities,LA,446,1308,1807,1389,869,...,336,842,438,302,280,225,101,168,318,NaN

In [9]:
# change names of columns

# first row new entries for the first four columns
occupation[[0, 0]] = 'CDU_ID'
occupation.head()

,CDU_ID,GEO_CODE,GEO_LABEL,GEO_TYPE,GEO_TYP2,F349793,F349800,F349807,F349814,F349821,...,F350017,F350024,F350031,F350038,F350045,F350052,F350059,Unnamed: 41,"(0, 0)",0
0,NaN,NaN,NaN,NaN,NaN,Age : Age 16 to 24 - Economic activity : Econo...,Age : Age 16 to 24 - Economic activity : Econo...,Age : Age 16 to 24 - Economic activity : Econo...,Age : Age 16 to 24 - Economic activity : Econo...,Age : Age 16 to 24 - Economic activity : Econo...,...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,Age : Age 65 and over - Economic activity : Ec...,NaN,CDU_ID,CDU_ID
1,374.0,E09000007,Camden,Local Authorities,LA,494,1936,2155,1241,396,...,983,436,203,212,185,142,340,NaN,CDU_ID,CDU_ID
2,379.0,E09000012,Hackney,Local Authorities,LA,535,2226,2628,1676,657,...,262,210,176,192,96,168,313,NaN,CDU_ID,CDU_ID
3,380.0,E09000013,Hammersmith and Fulham,Local Authorities,LA,570,2053,2459,1337,571,...,487,305,223,143,84,112,287,NaN,CDU_ID,CDU_ID
4,381.0,E09000014,Haringey,Local Authorities,LA,446,1308,1807,1389,869,...,438,302,280,225,101,168,318,NaN,CDU_ID,CDU_ID